view: eventque_union {
  derived_table: {
    distribution: "advertising_id"
    sql:

  (SELECT

  action,
  active_fail_safe_scenario,
  active_item_count,
  active_item_count_int,
  advertising_id,
  amount,
  app_version,
  apps_flyer_response_time,
  arrival_ts,
  asset,
  boosters,
  build_no,
  building_item_count,
  business_event_name,
  completed_ad_count,
  completed_rewarded_count_alltime,
  completed_rewarded_count_in_day,
  completed_rewarded_count_in_session,
  connection_type,
  conversion_data,
  currency_change_avatar_amount_type,
  currency_change_avatar_change_amount,
  currency_change_avatar_current_amount,
  currency_change_avatar_frame_amount_type,
  currency_change_avatar_frame_change_amount,
  currency_change_avatar_frame_current_amount,
  currency_change_coin_amount_type,
  currency_change_coin_change_amount,
  currency_change_coin_current_amount,
  currency_change_environment_token_amount_type,
  currency_change_environment_token_change_amount,
  currency_change_environment_token_current_amount,
  currency_change_event_score_multiplier_amount_type,
  currency_change_event_score_multiplier_change_amount,
  currency_change_event_score_multiplier_current_amount,
  currency_change_event_token_amount_type,
  currency_change_event_token_change_amount,
  currency_change_event_token_current_amount,
  currency_change_extra_slot_amount_type,
  currency_change_extra_slot_change_amount,
  currency_change_extra_slot_current_amount,
  currency_change_extra_time_amount_type,
  currency_change_extra_time_change_amount,
  currency_change_extra_time_current_amount,
  currency_change_glove_amount_type,
  currency_change_glove_change_amount,
  currency_change_glove_current_amount,
  currency_change_life_amount_type,
  currency_change_life_change_amount,
  currency_change_life_current_amount,
  currency_change_magic_wand_amount_type,
  currency_change_magic_wand_change_amount,
  currency_change_magic_wand_current_amount,
  currency_change_magnet_amount_type,
  currency_change_magnet_change_amount,
  currency_change_magnet_current_amount,
  currency_change_reward_multiplier_amount_type,
  currency_change_reward_multiplier_change_amount,
  currency_change_reward_multiplier_current_amount,
  currency_change_shuffle_amount_type,
  currency_change_shuffle_change_amount,
  currency_change_shuffle_current_amount,
  currency_change_time_freezer_amount_type,
  currency_change_time_freezer_change_amount,
  currency_change_time_freezer_current_amount,
  currency_change_toss_amount_type,
  currency_change_toss_change_amount,
  currency_change_toss_current_amount,
  currency_code,
  daily_day,
  daily_period_index,
  daily_reward_id,
  daily_reward_id_string,
  deeplink_event_args,
  difficulty,
  difficulty_rank,
  displayed_ad_count,
  displayed_ad_count_in_level,
  displayed_rewarded_count_alltime,
  displayed_rewarded_count_in_day,
  displayed_rewarded_count_in_session,
  duration,
  end_game_offer,
  end_game_offer_10_bonus_slot,
  end_game_offer_10_bonus_time,
  end_game_offer_10_fail_type,
  end_game_offer_10_offer_type,
  end_game_offer_1_bonus_slot,
  end_game_offer_1_bonus_time,
  end_game_offer_1_fail_type,
  end_game_offer_1_offer_type,
  end_game_offer_2_bonus_slot,
  end_game_offer_2_bonus_time,
  end_game_offer_2_fail_type,
  end_game_offer_2_offer_type,
  end_game_offer_3_bonus_slot,
  end_game_offer_3_bonus_time,
  end_game_offer_3_fail_type,
  end_game_offer_3_offer_type,
  end_game_offer_4_bonus_slot,
  end_game_offer_4_bonus_time,
  end_game_offer_4_fail_type,
  end_game_offer_4_offer_type,
  end_game_offer_5_bonus_slot,
  end_game_offer_5_bonus_time,
  end_game_offer_5_fail_type,
  end_game_offer_5_offer_type,
  end_game_offer_6_bonus_slot,
  end_game_offer_6_fail_type,
  end_game_offer_6_offer_type,
  end_game_offer_7_bonus_slot,
  end_game_offer_7_bonus_time,
  end_game_offer_7_fail_type,
  end_game_offer_7_offer_type,
  end_game_offer_8_bonus_slot,
  end_game_offer_8_bonus_time,
  end_game_offer_8_fail_type,
  end_game_offer_8_offer_type,
  end_game_offer_9_bonus_slot,
  end_game_offer_9_bonus_time,
  end_game_offer_9_fail_type,
  end_game_offer_9_offer_type,
  environment_id,
  error_string,
  event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  fail_type,
  goodwill_pass_purchase_details_pass_type,
  goodwill_pass_purchase_details_start_date,
  goodwill_pass_purchase_details_step,
  initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  item_id,
  last_input_time,
  live_ops_bonus_bank_max_score,
  live_ops_bonus_bank_reward_collected,
  live_ops_bonus_bank_score,
  live_ops_chest_index,
  live_ops_claimed_stage,
  live_ops_complete_ratio,
  live_ops_connection_error,
  live_ops_default_stage_cont,
  live_ops_default_stage_index,
  live_ops_difficulty
  live_ops_elo_rank,
  live_ops_engagement_type,
  live_ops_event_name,
  live_ops_id,
  live_ops_is_accepted,
  live_ops_is_bonus,
  live_ops_is_free,
  live_ops_pass_type,
  live_ops_purchase_source,
  live_ops_quest,
  live_ops_racers_group_id,
  live_ops_ranking,
  live_ops_score,
  live_ops_start_date
  live_ops_start_time,
  live_ops_step,
  live_ops_store_open_source,
  live_ops_target,
  live_ops_template_id,
  live_ops_type,
  min_day_condition,
  monthly_day,
  monthly_period_index,
  monthly_reward_id,
  monthly_reward_id_string,
  move_count,
  obstacles,
  occured_issue,
  package_coefficient,
  package_id,
  package_order
  pay_and_proceed_purchase_details_start_day,
  pay_and_proceed_purchase_details_step,
  pay_and_proceed_purchase_details_template_id,
  period_index,
  play_time_elo_score,
  position,
  previous_event_id,
  purchase_source,
  reason,
  receipt_info,
  remain_tile_count,
  request_time,
  response,
  response_time,
  rewarded_ad_limit_in_day,
  rewarded_ad_limit_in_session,
  rewarded_ad_type,
  rewards_avatar_amount,
  rewards_avatar_amount_type,
  rewards_avatar_frame_amount,
  rewards_avatar_frame_amount_type,
  rewards_bonus_slot_amount,
  rewards_bonus_slot_amount_type,
  rewards_bonus_time_amount,
  rewards_bonus_time_amount_type,
  rewards_coin_amount,
  rewards_coin_amount_type,
  rewards_environment_token_amount,
  rewards_environment_token_amount_type,
  rewards_event_score_multiplier_amount,
  rewards_event_score_multiplier_amount_type,
  rewards_event_token_amount,
  rewards_event_token_amount_type,
  rewards_extra_slot_amount,
  rewards_extra_slot_amount_type,
  rewards_extra_time_amount,
  rewards_extra_time_amount_type,
  rewards_glove_amount,
  rewards_glove_amount_type,
  rewards_life_amount,
  rewards_life_amount_type,
  rewards_magic_wand_amount,
  rewards_magic_wand_amount_type,
  rewards_magnet_amount,
  rewards_magnet_amount_type,
  rewards_reward_multiplier_amount,
  rewards_reward_multiplier_amount_type,
  rewards_shuffle_amount,
  rewards_shuffle_amount_type,
  rewards_time_freezer_amount,
  rewards_time_freezer_amount_type,
  rewards_toss_amount,
  rewards_toss_amount_type,
  session_id,
  session_time,
  source,
  special_offer_details_id,
  status,
  step,
  step_index,
  step_name,
  store_visit_source,
  streak_breaker,
  tap_count,
  targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  tiles_on_board,
  time_begin,
  time_remain,
  total_attempt_at_current_level,
  total_tile_count,
  try,
  tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  visible_area,
  welcome_back_day,
  welcome_back_period,
  win_count_elo_score

  FROM

  (SELECT

  NULL AS action,
  NULL AS active_fail_safe_scenario,
  NULL AS active_item_count,
  NULL AS active_item_count_int,
  advertising_id,
  amount,
  app_version,
  NULL AS apps_flyer_response_time,
  arrival_ts,
  NULL AS asset,
  NULL AS boosters,
  build_no,
  NULL AS building_item_count,
  business_event_name,
  completed_ad_count,
  completed_rewarded_count_alltime,
  completed_rewarded_count_in_day,
  completed_rewarded_count_in_session,
  connection_type,
  NULL AS conversion_data,
  currency_change_avatar_amount_type,
  currency_change_avatar_change_amount,
  currency_change_avatar_current_amount,
  currency_change_avatar_frame_amount_type,
  currency_change_avatar_frame_change_amount,
  currency_change_avatar_frame_current_amount,
  currency_change_coin_amount_type,
  currency_change_coin_change_amount,
  currency_change_coin_current_amount,
  currency_change_environment_token_amount_type,
  currency_change_environment_token_change_amount,
  currency_change_environment_token_current_amount,
  currency_change_event_score_multiplier_amount_type,
  currency_change_event_score_multiplier_change_amount,
  currency_change_event_score_multiplier_current_amount,
  currency_change_event_token_amount_type,
  currency_change_event_token_change_amount,
  currency_change_event_token_current_amount,
  currency_change_extra_slot_amount_type,
  currency_change_extra_slot_change_amount,
  currency_change_extra_slot_current_amount,
  currency_change_extra_time_amount_type,
  currency_change_extra_time_change_amount,
  currency_change_extra_time_current_amount,
  currency_change_glove_amount_type,
  currency_change_glove_change_amount,
  currency_change_glove_current_amount,
  currency_change_life_amount_type,
  currency_change_life_change_amount,
  currency_change_life_current_amount,
  currency_change_magic_wand_amount_type,
  currency_change_magic_wand_change_amount,
  currency_change_magic_wand_current_amount,
  currency_change_magnet_amount_type,
  currency_change_magnet_change_amount,
  currency_change_magnet_current_amount,
  currency_change_reward_multiplier_amount_type,
  currency_change_reward_multiplier_change_amount,
  currency_change_reward_multiplier_current_amount,
  currency_change_shuffle_amount_type,
  currency_change_shuffle_change_amount,
  currency_change_shuffle_current_amount,
  currency_change_time_freezer_amount_type,
  currency_change_time_freezer_change_amount,
  currency_change_time_freezer_current_amount,
  currency_change_toss_amount_type,
  currency_change_toss_change_amount,
  currency_change_toss_current_amount,
  currency_code,
  daily_day,
  daily_period_index,
  daily_reward_id,
  daily_reward_id_string,
  NULL AS deeplink_event_args,
  NULL AS difficulty,
  NULL AS difficulty_rank,
  displayed_ad_count,
  displayed_ad_count_in_level,
  displayed_rewarded_count_alltime,
  displayed_rewarded_count_in_day,
  displayed_rewarded_count_in_session,
  duration,
  NULL AS end_game_offer,
  NULL AS end_game_offer_10_bonus_slot,
  NULL AS end_game_offer_10_bonus_time,
  NULL AS end_game_offer_10_fail_type,
  NULL AS end_game_offer_10_offer_type,
  NULL AS end_game_offer_1_bonus_slot,
  NULL AS end_game_offer_1_bonus_time,
  NULL AS end_game_offer_1_fail_type,
  NULL AS end_game_offer_1_offer_type,
  NULL AS end_game_offer_2_bonus_slot,
  NULL AS end_game_offer_2_bonus_time,
  NULL AS end_game_offer_2_fail_type,
  NULL AS end_game_offer_2_offer_type,
  NULL AS end_game_offer_3_bonus_slot,
  NULL AS end_game_offer_3_bonus_time,
  NULL AS end_game_offer_3_fail_type,
  NULL AS end_game_offer_3_offer_type,
  NULL AS end_game_offer_4_bonus_slot,
  NULL AS end_game_offer_4_bonus_time,
  NULL AS end_game_offer_4_fail_type,
  NULL AS end_game_offer_4_offer_type,
  NULL AS end_game_offer_5_bonus_slot,
  NULL AS end_game_offer_5_bonus_time,
  NULL AS end_game_offer_5_fail_type,
  NULL AS end_game_offer_5_offer_type,
  NULL AS end_game_offer_6_bonus_slot,
  NULL AS end_game_offer_6_fail_type,
  NULL AS end_game_offer_6_offer_type,
  NULL AS end_game_offer_7_bonus_slot,
  NULL AS end_game_offer_7_bonus_time,
  NULL AS end_game_offer_7_fail_type,
  NULL AS end_game_offer_7_offer_type,
  NULL AS end_game_offer_8_bonus_slot,
  NULL AS end_game_offer_8_bonus_time,
  NULL AS end_game_offer_8_fail_type,
  NULL AS end_game_offer_8_offer_type,
  NULL AS end_game_offer_9_bonus_slot,
  NULL AS end_game_offer_9_bonus_time,
  NULL AS end_game_offer_9_fail_type,
  NULL AS end_game_offer_9_offer_type,
  NULL AS environment_id,
  NULL AS error_string,
  event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  NULL AS fail_type,
  goodwill_pass_purchase_details_pass_type,
  goodwill_pass_purchase_details_start_date,
  goodwill_pass_purchase_details_step,
  initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  NULL AS item_id,
  NULL AS last_input_time,
  NULL AS live_ops_bonus_bank_max_score,
  NULL AS live_ops_bonus_bank_reward_collected,
  NULL AS live_ops_bonus_bank_score,
  NULL AS live_ops_chest_index,
  NULL AS live_ops_claimed_stage,
  NULL AS live_ops_complete_ratio,
  NULL AS live_ops_connection_error,
  NULL AS live_ops_default_stage_count,
  NULL AS live_ops_default_stage_index,
  NULL AS live_ops_difficulty,
  NULL AS live_ops_elo_rank,
  NULL AS live_ops_engagement_type,
  NULL AS live_ops_event_name,
  NULL AS live_ops_id,
  NULL AS live_ops_is_accepted,
  NULL AS live_ops_is_bonus,
  NULL AS live_ops_is_free,
  NULL AS live_ops_pass_type,
  NULL AS live_ops_purchase_source,
  NULL AS live_ops_quest,
  NULL AS live_ops_racers_group_id,
  NULL AS live_ops_ranking,
  NULL AS live_ops_score,
  NULL AS live_ops_start_date,
  NULL AS live_ops_start_time,
  NULL AS live_ops_step,
  NULL AS live_ops_store_open_source,
  NULL AS live_ops_target,
  NULL AS live_ops_template_id,
  NULL AS live_ops_type,
  min_day_condition,
  monthly_day,
  monthly_period_index,
  monthly_reward_id,
  monthly_reward_id_string,
  NULL AS move_count,
  NULL AS obstacles,
  NULL AS occured_issue,
  package_coefficient,
  package_id,
  NULL AS package_order,
  pay_and_proceed_purchase_details_start_day,
  pay_and_proceed_purchase_details_step,
  pay_and_proceed_purchase_details_template_id,
  NULL AS period_index,
  NULL AS play_time_elo_score,
  position,
  NULL AS previous_event_id,
  purchase_source,
  NULL AS reason,
  receipt_info,
  NULL AS remain_tile_count,
  request_time,
  NULL AS response,
  NULL AS response_time,
  rewarded_ad_limit_in_day,
  rewarded_ad_limit_in_session,
  rewarded_ad_type,
  rewards_avatar_amount,
  rewards_avatar_amount_type,
  rewards_avatar_frame_amount,
  rewards_avatar_frame_amount_type,
  rewards_bonus_slot_amount,
  rewards_bonus_slot_amount_type,
  rewards_bonus_time_amount,
  rewards_bonus_time_amount_type,
  rewards_coin_amount,
  rewards_coin_amount_type,
  rewards_environment_token_amount,
  rewards_environment_token_amount_type,
  rewards_event_score_multiplier_amount,
  rewards_event_score_multiplier_amount_type,
  rewards_event_token_amount,
  rewards_event_token_amount_type,
  rewards_extra_slot_amount,
  rewards_extra_slot_amount_type,
  rewards_extra_time_amount,
  rewards_extra_time_amount_type,
  rewards_glove_amount,
  rewards_glove_amount_type,
  rewards_life_amount,
  rewards_life_amount_type,
  rewards_magic_wand_amount,
  rewards_magic_wand_amount_type,
  rewards_magnet_amount,
  rewards_magnet_amount_type,
  rewards_reward_multiplier_amount,
  rewards_reward_multiplier_amount_type,
  rewards_shuffle_amount,
  rewards_shuffle_amount_type,
  rewards_time_freezer_amount,
  rewards_time_freezer_amount_type,
  rewards_toss_amount,
  rewards_toss_amount_type,
  session_id,
  session_time,
  source,
  special_offer_details_id,
  status,
  NULL AS step,
  NULL AS step_index,
  NULL AS step_name,
  store_visit_source,
  NULL AS streak_breaker,
  NULL AS tap_count,
  NULL AS targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  NULL AS tiles_on_board,
  NULL AS time_begin,
  NULL AS time_remain,
  NULL AS total_attempt_at_current_level,
  NULL AS total_tile_count,
  NULL AS try,
  NULL AS tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  NULL AS user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  NULL AS user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  visible_area,
  welcome_back_day,
  welcome_back_period,
  NULL AS win_count_elo_score

FROM
  tile_match.business

UNION ALL

SELECT
  NULL AS action,
  NULL AS active_fail_safe_scenario,
  active_item_count,
  active_item_count_int,
  advertising_id,
  NULL AS amount,
  app_version,
  NULL AS apps_flyer_response_time,
  arrival_ts,
  NULL AS asset,
  NULL AS boosters,
  build_no,
  building_item_count,
  NULL AS business_event_name,
  NULL AS completed_ad_count,
  NULL AS completed_rewarded_count_alltime,
  NULL AS completed_rewarded_count_in_day,
  NULL AS completed_rewarded_count_in_session,
  connection_type,
  NULL AS conversion_data,
  NULL AS currency_change_avatar_amount_type,
  NULL AS currency_change_avatar_change_amount,
  NULL AS currency_change_avatar_current_amount,
  NULL AS currency_change_avatar_frame_amount_type,
  NULL AS currency_change_avatar_frame_change_amount,
  NULL AS currency_change_avatar_frame_current_amount,
  NULL AS currency_change_coin_amount_type,
  NULL AS currency_change_coin_change_amount,
  NULL AS currency_change_coin_current_amount,
  NULL AS currency_change_environment_token_amount_type,
  NULL AS currency_change_environment_token_change_amount,
  NULL AS currency_change_environment_token_current_amount,
  NULL AS currency_change_event_score_multiplier_amount_type,
  NULL AS currency_change_event_score_multiplier_change_amount,
  NULL AS currency_change_event_score_multiplier_current_amount,
  NULL AS currency_change_event_token_amount_type,
  NULL AS currency_change_event_token_change_amount,
  NULL AS currency_change_event_token_current_amount,
  NULL AS currency_change_extra_slot_amount_type,
  NULL AS currency_change_extra_slot_change_amount,
  NULL AS currency_change_extra_slot_current_amount,
  NULL AS currency_change_extra_time_amount_type,
  NULL AS currency_change_extra_time_change_amount,
  NULL AS currency_change_extra_time_current_amount,
  NULL AS currency_change_glove_amount_type,
  NULL AS currency_change_glove_change_amount,
  NULL AS currency_change_glove_current_amount,
  NULL AS currency_change_life_amount_type,
  NULL AS currency_change_life_change_amount,
  NULL AS currency_change_life_current_amount,
  NULL AS currency_change_magic_wand_amount_type,
  NULL AS currency_change_magic_wand_change_amount,
  NULL AS currency_change_magic_wand_current_amount,
  NULL AS currency_change_magnet_amount_type,
  NULL AS currency_change_magnet_change_amount,
  NULL AS currency_change_magnet_current_amount,
  NULL AS currency_change_reward_multiplier_amount_type,
  NULL AS currency_change_reward_multiplier_change_amount,
  NULL AS currency_change_reward_multiplier_current_amount,
  NULL AS currency_change_shuffle_amount_type,
  NULL AS currency_change_shuffle_change_amount,
  NULL AS currency_change_shuffle_current_amount,
  NULL AS currency_change_time_freezer_amount_type,
  NULL AS currency_change_time_freezer_change_amount,
  NULL AS currency_change_time_freezer_current_amount,
  NULL AS currency_change_toss_amount_type,
  NULL AS currency_change_toss_change_amount,
  NULL AS currency_change_toss_current_amount,
  NULL AS currency_code,
  NULL AS daily_day,
  NULL AS daily_period_index,
  NULL AS daily_reward_id,
  NULL AS daily_reward_id_string,
  NULL AS deeplink_event_args,
  NULL AS difficulty,
  NULL AS difficulty_rank,
  NULL AS displayed_ad_count,
  NULL AS displayed_ad_count_in_level,
  NULL AS displayed_rewarded_count_alltime,
  NULL AS displayed_rewarded_count_in_day,
  NULL AS displayed_rewarded_count_in_session,
  duration,
  NULL AS end_game_offer,
  NULL AS end_game_offer_10_bonus_slot,
  NULL AS end_game_offer_10_bonus_time,
  NULL AS end_game_offer_10_fail_type,
  NULL AS end_game_offer_10_offer_type,
  NULL AS end_game_offer_1_bonus_slot,
  NULL AS end_game_offer_1_bonus_time,
  NULL AS end_game_offer_1_fail_type,
  NULL AS end_game_offer_1_offer_type,
  NULL AS end_game_offer_2_bonus_slot,
  NULL AS end_game_offer_2_bonus_time,
  NULL AS end_game_offer_2_fail_type,
  NULL AS end_game_offer_2_offer_type,
  NULL AS end_game_offer_3_bonus_slot,
  NULL AS end_game_offer_3_bonus_time,
  NULL AS end_game_offer_3_fail_type,
  NULL AS end_game_offer_3_offer_type,
  NULL AS end_game_offer_4_bonus_slot,
  NULL AS end_game_offer_4_bonus_time,
  NULL AS end_game_offer_4_fail_type,
  NULL AS end_game_offer_4_offer_type,
  NULL AS end_game_offer_5_bonus_slot,
  NULL AS end_game_offer_5_bonus_time,
  NULL AS end_game_offer_5_fail_type,
  NULL AS end_game_offer_5_offer_type,
  NULL AS end_game_offer_6_bonus_slot,
  NULL AS end_game_offer_6_fail_type,
  NULL AS end_game_offer_6_offer_type,
  NULL AS end_game_offer_7_bonus_slot,
  NULL AS end_game_offer_7_bonus_time,
  NULL AS end_game_offer_7_fail_type,
  NULL AS end_game_offer_7_offer_type,
  NULL AS end_game_offer_8_bonus_slot,
  NULL AS end_game_offer_8_bonus_time,
  NULL AS end_game_offer_8_fail_type,
  NULL AS end_game_offer_8_offer_type,
  NULL AS end_game_offer_9_bonus_slot,
  NULL AS end_game_offer_9_bonus_time,
  NULL AS end_game_offer_9_fail_type,
  NULL AS end_game_offer_9_offer_type,
  environment_id,
  NULL AS error_string,
  NULL AS event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  NULL AS fail_type,
  NULL AS goodwill_pass_purchase_details_pass_type,
  NULL AS goodwill_pass_purchase_details_start_date,
  NULL AS goodwill_pass_purchase_details_step,
  NULL AS initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  item_id,
  NULL AS last_input_time,
  live_ops_bonus_bank_max_score,
  live_ops_bonus_bank_reward_collected,
  live_ops_bonus_bank_score,
  live_ops_chest_index,
  live_ops_claimed_stage,
  live_ops_complete_ratio,
  live_ops_connection_error,
  live_ops_default_stage_count,
  live_ops_default_stage_index,
  live_ops_difficulty,
  live_ops_elo_rank,
  live_ops_engagement_type,
  live_ops_event_name,
  live_ops_id,
  live_ops_is_accepted,
  live_ops_is_bonus,
  live_ops_is_free,
  live_ops_pass_type,
  live_ops_purchase_source,
  live_ops_quest,
  live_ops_racers_group_id,
  live_ops_ranking,
  live_ops_score,
  live_ops_start_date,
  live_ops_start_time,
  live_ops_step,
  live_ops_store_open_source,
  live_ops_target,
  live_ops_template_id,
  live_ops_type,
  NULL AS min_day_condition,
  NULL AS monthly_day,
  NULL AS monthly_period_index,
  NULL AS monthly_reward_id,
  NULL AS monthly_reward_id_string,
  NULL AS move_count,
  NULL AS obstacles,
  NULL AS occured_issue,
  NULL AS package_coefficient,
  NULL AS package_id,
  package_order,
  NULL AS pay_and_proceed_purchase_details_start_day,
  NULL AS pay_and_proceed_purchase_details_step,
  NULL AS pay_and_proceed_purchase_details_template_id,
  NULL AS period_index,
  play_time_elo_score,
  NULL AS position,
  NULL AS previous_event_id,
  NULL AS purchase_source,
  NULL AS reason,
  NULL AS receipt_info,
  NULL AS remain_tile_count,
  request_time,
  NULL AS response,
  NULL AS response_time,
  NULL AS rewarded_ad_limit_in_day,
  NULL AS rewarded_ad_limit_in_session,
  NULL AS rewarded_ad_type,
  NULL AS rewards_avatar_amount,
  NULL AS rewards_avatar_amount_type,
  NULL AS rewards_avatar_frame_amount,
  NULL AS rewards_avatar_frame_amount_type,
  NULL AS rewards_bonus_slot_amount,
  NULL AS rewards_bonus_slot_amount_type,
  NULL AS rewards_bonus_time_amount,
  NULL AS rewards_bonus_time_amount_type,
  NULL AS rewards_coin_amount,
  NULL AS rewards_coin_amount_type,
  NULL AS rewards_environment_token_amount,
  NULL AS rewards_environment_token_amount_type,
  NULL AS rewards_event_score_multiplier_amount,
  NULL AS rewards_event_score_multiplier_amount_type,
  NULL AS rewards_event_token_amount,
  NULL AS rewards_event_token_amount_type,
  NULL AS rewards_extra_slot_amount,
  NULL AS rewards_extra_slot_amount_type,
  NULL AS rewards_extra_time_amount,
  NULL AS rewards_extra_time_amount_type,
  NULL AS rewards_glove_amount,
  NULL AS rewards_glove_amount_type,
  NULL AS rewards_life_amount,
  NULL AS rewards_life_amount_type,
  NULL AS rewards_magic_wand_amount,
  NULL AS rewards_magic_wand_amount_type,
  NULL AS rewards_magnet_amount,
  NULL AS rewards_magnet_amount_type,
  NULL AS rewards_reward_multiplier_amount,
  NULL AS rewards_reward_multiplier_amount_type,
  NULL AS rewards_shuffle_amount,
  NULL AS rewards_shuffle_amount_type,
  NULL AS rewards_time_freezer_amount,
  NULL AS rewards_time_freezer_amount_type,
  NULL AS rewards_toss_amount,
  NULL AS rewards_toss_amount_type,
  session_id,
  session_time,
  NULL AS source,
  NULL AS special_offer_details_id,
  NULL AS status,
  NULL AS step,
  NULL AS step_index,
  NULL AS step_name,
  NULL AS store_visit_source,
  NULL AS streak_breaker,
  tap_count,
  NULL AS targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  NULL AS tiles_on_board,
  NULL AS time_begin,
  NULL AS time_remain,
  NULL AS total_attempt_at_current_level,
  NULL AS total_tile_count,
  NULL AS try,
  NULL AS tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  NULL AS user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  NULL AS user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  NULL AS visible_area,
  NULL AS welcome_back_day,
  NULL AS welcome_back_period,
  win_count_elo_score

FROM
  tile_match.live_ops

UNION ALL

SELECT
  action,
  NULL AS active_fail_safe_scenario,
  NULL AS active_item_count,
  NULL AS active_item_count_int,
  advertising_id,
  NULL AS amount,
  app_version,
  apps_flyer_response_time,
  arrival_ts,
  asset,
  NULL AS boosters,
  build_no,
  NULL AS building_item_count,
  NULL AS business_event_name,
  NULL AS completed_ad_count,
  NULL AS completed_rewarded_count_alltime,
  NULL AS completed_rewarded_count_in_day,
  NULL AS completed_rewarded_count_in_session,
  connection_type,
  conversion_data,
  NULL AS currency_change_avatar_amount_type,
  NULL AS currency_change_avatar_change_amount,
  NULL AS currency_change_avatar_current_amount,
  NULL AS currency_change_avatar_frame_amount_type,
  NULL AS currency_change_avatar_frame_change_amount,
  NULL AS currency_change_avatar_frame_current_amount,
  NULL AS currency_change_coin_amount_type,
  NULL AS currency_change_coin_change_amount,
  NULL AS currency_change_coin_current_amount,
  NULL AS currency_change_environment_token_amount_type,
  NULL AS currency_change_environment_token_change_amount,
  NULL AS currency_change_environment_token_current_amount,
  NULL AS currency_change_event_score_multiplier_amount_type,
  NULL AS currency_change_event_score_multiplier_change_amount,
  NULL AS currency_change_event_score_multiplier_current_amount,
  NULL AS currency_change_event_token_amount_type,
  NULL AS currency_change_event_token_change_amount,
  NULL AS currency_change_event_token_current_amount,
  NULL AS currency_change_extra_slot_amount_type,
  NULL AS currency_change_extra_slot_change_amount,
  NULL AS currency_change_extra_slot_current_amount,
  NULL AS currency_change_extra_time_amount_type,
  NULL AS currency_change_extra_time_change_amount,
  NULL AS currency_change_extra_time_current_amount,
  NULL AS currency_change_glove_amount_type,
  NULL AS currency_change_glove_change_amount,
  NULL AS currency_change_glove_current_amount,
  NULL AS currency_change_life_amount_type,
  NULL AS currency_change_life_change_amount,
  NULL AS currency_change_life_current_amount,
  NULL AS currency_change_magic_wand_amount_type,
  NULL AS currency_change_magic_wand_change_amount,
  NULL AS currency_change_magic_wand_current_amount,
  NULL AS currency_change_magnet_amount_type,
  NULL AS currency_change_magnet_change_amount,
  NULL AS currency_change_magnet_current_amount,
  NULL AS currency_change_reward_multiplier_amount_type,
  NULL AS currency_change_reward_multiplier_change_amount,
  NULL AS currency_change_reward_multiplier_current_amount,
  NULL AS currency_change_shuffle_amount_type,
  NULL AS currency_change_shuffle_change_amount,
  NULL AS currency_change_shuffle_current_amount,
  NULL AS currency_change_time_freezer_amount_type,
  NULL AS currency_change_time_freezer_change_amount,
  NULL AS currency_change_time_freezer_current_amount,
  NULL AS currency_change_toss_amount_type,
  NULL AS currency_change_toss_change_amount,
  NULL AS currency_change_toss_current_amount,
  NULL AS currency_code,
  NULL AS daily_day,
  NULL AS daily_period_index,
  NULL AS daily_reward_id,
  NULL AS daily_reward_id_string,
  deeplink_event_args,
  NULL AS difficulty,
  NULL AS difficulty_rank,
  NULL AS displayed_ad_count,
  NULL AS displayed_ad_count_in_level,
  NULL AS displayed_rewarded_count_alltime,
  NULL AS displayed_rewarded_count_in_day,
  NULL AS displayed_rewarded_count_in_session,
  duration,
  NULL AS end_game_offer,
  NULL AS end_game_offer_10_bonus_slot,
  NULL AS end_game_offer_10_bonus_time,
  NULL AS end_game_offer_10_fail_type,
  NULL AS end_game_offer_10_offer_type,
  NULL AS end_game_offer_1_bonus_slot,
  NULL AS end_game_offer_1_bonus_time,
  NULL AS end_game_offer_1_fail_type,
  NULL AS end_game_offer_1_offer_type,
  NULL AS end_game_offer_2_bonus_slot,
  NULL AS end_game_offer_2_bonus_time,
  NULL AS end_game_offer_2_fail_type,
  NULL AS end_game_offer_2_offer_type,
  NULL AS end_game_offer_3_bonus_slot,
  NULL AS end_game_offer_3_bonus_time,
  NULL AS end_game_offer_3_fail_type,
  NULL AS end_game_offer_3_offer_type,
  NULL AS end_game_offer_4_bonus_slot,
  NULL AS end_game_offer_4_bonus_time,
  NULL AS end_game_offer_4_fail_type,
  NULL AS end_game_offer_4_offer_type,
  NULL AS end_game_offer_5_bonus_slot,
  NULL AS end_game_offer_5_bonus_time,
  NULL AS end_game_offer_5_fail_type,
  NULL AS end_game_offer_5_offer_type,
  NULL AS end_game_offer_6_bonus_slot,
  NULL AS end_game_offer_6_fail_type,
  NULL AS end_game_offer_6_offer_type,
  NULL AS end_game_offer_7_bonus_slot,
  NULL AS end_game_offer_7_bonus_time,
  NULL AS end_game_offer_7_fail_type,
  NULL AS end_game_offer_7_offer_type,
  NULL AS end_game_offer_8_bonus_slot,
  NULL AS end_game_offer_8_bonus_time,
  NULL AS end_game_offer_8_fail_type,
  NULL AS end_game_offer_8_offer_type,
  NULL AS end_game_offer_9_bonus_slot,
  NULL AS end_game_offer_9_bonus_time,
  NULL AS end_game_offer_9_fail_type,
  NULL AS end_game_offer_9_offer_type,
  NULL AS environment_id,
  error_string,
  NULL AS event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  NULL AS fail_type,
  NULL AS goodwill_pass_purchase_details_pass_type,
  NULL AS goodwill_pass_purchase_details_start_date,
  NULL AS goodwill_pass_purchase_details_step,
  NULL AS initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  NULL AS item_id,
  NULL AS last_input_time,
  NULL AS live_ops_bonus_bank_max_score,
  NULL AS live_ops_bonus_bank_reward_collected,
  NULL AS live_ops_bonus_bank_score,
  NULL AS live_ops_chest_index,
  NULL AS live_ops_claimed_stage,
  NULL AS live_ops_complete_ratio,
  NULL AS live_ops_connection_error,
  NULL AS live_ops_default_stage_count,
  NULL AS live_ops_default_stage_index,
  NULL AS live_ops_difficulty,
  NULL AS live_ops_elo_rank,
  NULL AS live_ops_engagement_type,
  NULL AS live_ops_event_name,
  NULL AS live_ops_id,
  NULL AS live_ops_is_accepted,
  NULL AS live_ops_is_bonus,
  NULL AS live_ops_is_free,
  NULL AS live_ops_pass_type,
  NULL AS live_ops_purchase_source,
  NULL AS live_ops_quest,
  NULL AS live_ops_racers_group_id,
  NULL AS live_ops_ranking,
  NULL AS live_ops_score,
  NULL AS live_ops_start_date,
  NULL AS live_ops_start_time,
  NULL AS live_ops_step,
  NULL AS live_ops_store_open_source,
  NULL AS live_ops_target,
  NULL AS live_ops_template_id,
  NULL AS live_ops_type,
  NULL AS min_day_condition,
  NULL AS monthly_day,
  NULL AS monthly_period_index,
  NULL AS monthly_reward_id,
  NULL AS monthly_reward_id_string,
  NULL AS move_count,
  NULL AS obstacles,
  occured_issue,
  NULL AS package_coefficient,
  NULL AS package_id,
  NULL AS package_order,
  NULL AS pay_and_proceed_purchase_details_start_day,
  NULL AS pay_and_proceed_purchase_details_step,
  NULL AS pay_and_proceed_purchase_details_template_id,
  period_index,
  NULL AS play_time_elo_score,
  NULL AS position,
  NULL AS previous_event_id,
  NULL AS purchase_source,
  reason,
  NULL AS receipt_info,
  NULL AS remain_tile_count,
  request_time,
  response,
  response_time,
  NULL AS rewarded_ad_limit_in_day,
  NULL AS rewarded_ad_limit_in_session,
  NULL AS rewarded_ad_type,
  NULL AS rewards_avatar_amount,
  NULL AS rewards_avatar_amount_type,
  NULL AS rewards_avatar_frame_amount,
  NULL AS rewards_avatar_frame_amount_type,
  NULL AS rewards_bonus_slot_amount,
  NULL AS rewards_bonus_slot_amount_type,
  NULL AS rewards_bonus_time_amount,
  NULL AS rewards_bonus_time_amount_type,
  NULL AS rewards_coin_amount,
  NULL AS rewards_coin_amount_type,
  NULL AS rewards_environment_token_amount,
  NULL AS rewards_environment_token_amount_type,
  NULL AS rewards_event_score_multiplier_amount,
  NULL AS rewards_event_score_multiplier_amount_type,
  NULL AS rewards_event_token_amount,
  NULL AS rewards_event_token_amount_type,
  NULL AS rewards_extra_slot_amount,
  NULL AS rewards_extra_slot_amount_type,
  NULL AS rewards_extra_time_amount,
  NULL AS rewards_extra_time_amount_type,
  NULL AS rewards_glove_amount,
  NULL AS rewards_glove_amount_type,
  NULL AS rewards_life_amount,
  NULL AS rewards_life_amount_type,
  NULL AS rewards_magic_wand_amount,
  NULL AS rewards_magic_wand_amount_type,
  NULL AS rewards_magnet_amount,
  NULL AS rewards_magnet_amount_type,
  NULL AS rewards_reward_multiplier_amount,
  NULL AS rewards_reward_multiplier_amount_type,
  NULL AS rewards_shuffle_amount,
  NULL AS rewards_shuffle_amount_type,
  NULL AS rewards_time_freezer_amount,
  NULL AS rewards_time_freezer_amount_type,
  NULL AS rewards_toss_amount,
  NULL AS rewards_toss_amount_type,
  session_id,
  session_time,
  NULL AS source,
  NULL AS special_offer_details_id,
  NULL AS status,
  step,
  step_index,
  step_name,
  NULL AS store_visit_source,
  NULL AS streak_breaker,
  NULL AS tap_count,
  NULL AS targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  NULL AS tiles_on_board,
  NULL AS time_begin,
  NULL AS time_remain,
  NULL AS total_attempt_at_current_level,
  NULL AS total_tile_count,
  try,
  tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  NULL AS visible_area,
  NULL AS welcome_back_day,
  NULL AS welcome_back_period,
  NULL AS win_count_elo_score

FROM
  tile_match.monitoring

UNION ALL

SELECT
  NULL AS action,
  active_fail_safe_scenario,
  NULL AS active_item_count,
  NULL AS active_item_count_int,
  advertising_id,
  NULL AS amount,
  app_version,
  NULL AS apps_flyer_response_time,
  arrival_ts,
  NULL AS asset,
  boosters,
  build_no,
  NULL AS building_item_count,
  NULL AS business_event_name,
  NULL AS completed_ad_count,
  NULL AS completed_rewarded_count_alltime,
  NULL AS completed_rewarded_count_in_day,
  NULL AS completed_rewarded_count_in_session,
  connection_type,
  NULL AS conversion_data,
  NULL AS currency_change_avatar_amount_type,
  NULL AS currency_change_avatar_change_amount,
  NULL AS currency_change_avatar_current_amount,
  NULL AS currency_change_avatar_frame_amount_type,
  NULL AS currency_change_avatar_frame_change_amount,
  NULL AS currency_change_avatar_frame_current_amount,
  NULL AS currency_change_coin_amount_type,
  NULL AS currency_change_coin_change_amount,
  NULL AS currency_change_coin_current_amount,
  NULL AS currency_change_environment_token_amount_type,
  NULL AS currency_change_environment_token_change_amount,
  NULL AS currency_change_environment_token_current_amount,
  NULL AS currency_change_event_score_multiplier_amount_type,
  NULL AS currency_change_event_score_multiplier_change_amount,
  NULL AS currency_change_event_score_multiplier_current_amount,
  NULL AS currency_change_event_token_amount_type,
  NULL AS currency_change_event_token_change_amount,
  NULL AS currency_change_event_token_current_amount,
  NULL AS currency_change_extra_slot_amount_type,
  NULL AS currency_change_extra_slot_change_amount,
  NULL AS currency_change_extra_slot_current_amount,
  NULL AS currency_change_extra_time_amount_type,
  NULL AS currency_change_extra_time_change_amount,
  NULL AS currency_change_extra_time_current_amount,
  NULL AS currency_change_glove_amount_type,
  NULL AS currency_change_glove_change_amount,
  NULL AS currency_change_glove_current_amount,
  NULL AS currency_change_life_amount_type,
  NULL AS currency_change_life_change_amount,
  NULL AS currency_change_life_current_amount,
  NULL AS currency_change_magic_wand_amount_type,
  NULL AS currency_change_magic_wand_change_amount,
  NULL AS currency_change_magic_wand_current_amount,
  NULL AS currency_change_magnet_amount_type,
  NULL AS currency_change_magnet_change_amount,
  NULL AS currency_change_magnet_current_amount,
  NULL AS currency_change_reward_multiplier_amount_type,
  NULL AS currency_change_reward_multiplier_change_amount,
  NULL AS currency_change_reward_multiplier_current_amount,
  NULL AS currency_change_shuffle_amount_type,
  NULL AS currency_change_shuffle_change_amount,
  NULL AS currency_change_shuffle_current_amount,
  NULL AS currency_change_time_freezer_amount_type,
  NULL AS currency_change_time_freezer_change_amount,
  NULL AS currency_change_time_freezer_current_amount,
  NULL AS currency_change_toss_amount_type,
  NULL AS currency_change_toss_change_amount,
  NULL AS currency_change_toss_current_amount,
  NULL AS currency_code,
  NULL AS daily_day,
  NULL AS daily_period_index,
  NULL AS daily_reward_id,
  NULL AS daily_reward_id_string,
  NULL AS deeplink_event_args,
  difficulty,
  difficulty_rank,
  NULL AS displayed_ad_count,
  NULL AS displayed_ad_count_in_level,
  NULL AS displayed_rewarded_count_alltime,
  NULL AS displayed_rewarded_count_in_day,
  NULL AS displayed_rewarded_count_in_session,
  NULL AS duration,
  end_game_offer,
  end_game_offer_10_bonus_slot,
  end_game_offer_10_bonus_time,
  end_game_offer_10_fail_type,
  end_game_offer_10_offer_type,
  end_game_offer_1_bonus_slot,
  end_game_offer_1_bonus_time,
  end_game_offer_1_fail_type,
  end_game_offer_1_offer_type,
  end_game_offer_2_bonus_slot,
  end_game_offer_2_bonus_time,
  end_game_offer_2_fail_type,
  end_game_offer_2_offer_type,
  end_game_offer_3_bonus_slot,
  end_game_offer_3_bonus_time,
  end_game_offer_3_fail_type,
  end_game_offer_3_offer_type,
  end_game_offer_4_bonus_slot,
  end_game_offer_4_bonus_time,
  end_game_offer_4_fail_type,
  end_game_offer_4_offer_type,
  end_game_offer_5_bonus_slot,
  end_game_offer_5_bonus_time,
  end_game_offer_5_fail_type,
  end_game_offer_5_offer_type,
  end_game_offer_6_bonus_slot,
  end_game_offer_6_fail_type,
  end_game_offer_6_offer_type,
  end_game_offer_7_bonus_slot,
  end_game_offer_7_bonus_time,
  end_game_offer_7_fail_type,
  end_game_offer_7_offer_type,
  end_game_offer_8_bonus_slot,
  end_game_offer_8_bonus_time,
  end_game_offer_8_fail_type,
  end_game_offer_8_offer_type,
  end_game_offer_9_bonus_slot,
  end_game_offer_9_bonus_time,
  end_game_offer_9_fail_type,
  end_game_offer_9_offer_type,
  NULL AS environment_id,
  NULL AS error_string,
  NULL AS event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  fail_type,
  NULL AS goodwill_pass_purchase_details_pass_type,
  NULL AS goodwill_pass_purchase_details_start_date,
  NULL AS goodwill_pass_purchase_details_step,
  NULL AS initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  NULL AS item_id,
  last_input_time,
  NULL AS live_ops_bonus_bank_max_score,
  NULL AS live_ops_bonus_bank_reward_collected,
  NULL AS live_ops_bonus_bank_score,
  NULL AS live_ops_chest_index,
  NULL AS live_ops_claimed_stage,
  NULL AS live_ops_complete_ratio,
  NULL AS live_ops_connection_error,
  NULL AS live_ops_default_stage_count,
  NULL AS live_ops_default_stage_index,
  NULL AS live_ops_difficulty,
  NULL AS live_ops_elo_rank,
  NULL AS live_ops_engagement_type,
  NULL AS live_ops_event_name,
  NULL AS live_ops_id,
  NULL AS live_ops_is_accepted,
  NULL AS live_ops_is_bonus,
  NULL AS live_ops_is_free,
  NULL AS live_ops_pass_type,
  NULL AS live_ops_purchase_source,
  NULL AS live_ops_quest,
  NULL AS live_ops_racers_group_id,
  NULL AS live_ops_ranking,
  NULL AS live_ops_score,
  NULL AS live_ops_start_date,
  NULL AS live_ops_start_time,
  NULL AS live_ops_step,
  NULL AS live_ops_store_open_source,
  NULL AS live_ops_target,
  NULL AS live_ops_template_id,
  NULL AS live_ops_type,
  NULL AS min_day_condition,
  NULL AS monthly_day,
  NULL AS monthly_period_index,
  NULL AS monthly_reward_id,
  NULL AS monthly_reward_id_string,
  move_count,
  obstacles,
  NULL AS occured_issue,
  NULL AS package_coefficient,
  NULL AS package_id,
  NULL AS package_order,
  NULL AS pay_and_proceed_purchase_details_start_day,
  NULL AS pay_and_proceed_purchase_details_step,
  NULL AS pay_and_proceed_purchase_details_template_id,
  NULL AS period_index,
  NULL AS play_time_elo_score,
  NULL AS position,
  previous_event_id,
  NULL AS purchase_source,
  NULL AS reason,
  NULL AS receipt_info,
  remain_tile_count,
  request_time,
  NULL AS response,
  NULL AS response_time,
  NULL AS rewarded_ad_limit_in_day,
  NULL AS rewarded_ad_limit_in_session,
  NULL AS rewarded_ad_type,
  NULL AS rewards_avatar_amount,
  NULL AS rewards_avatar_amount_type,
  NULL AS rewards_avatar_frame_amount,
  NULL AS rewards_avatar_frame_amount_type,
  NULL AS rewards_bonus_slot_amount,
  NULL AS rewards_bonus_slot_amount_type,
  NULL AS rewards_bonus_time_amount,
  NULL AS rewards_bonus_time_amount_type,
  NULL AS rewards_coin_amount,
  NULL AS rewards_coin_amount_type,
  NULL AS rewards_environment_token_amount,
  NULL AS rewards_environment_token_amount_type,
  NULL AS rewards_event_score_multiplier_amount,
  NULL AS rewards_event_score_multiplier_amount_type,
  NULL AS rewards_event_token_amount,
  NULL AS rewards_event_token_amount_type,
  NULL AS rewards_extra_slot_amount,
  NULL AS rewards_extra_slot_amount_type,
  NULL AS rewards_extra_time_amount,
  NULL AS rewards_extra_time_amount_type,
  NULL AS rewards_glove_amount,
  NULL AS rewards_glove_amount_type,
  NULL AS rewards_life_amount,
  NULL AS rewards_life_amount_type,
  NULL AS rewards_magic_wand_amount,
  NULL AS rewards_magic_wand_amount_type,
  NULL AS rewards_magnet_amount,
  NULL AS rewards_magnet_amount_type,
  NULL AS rewards_reward_multiplier_amount,
  NULL AS rewards_reward_multiplier_amount_type,
  NULL AS rewards_shuffle_amount,
  NULL AS rewards_shuffle_amount_type,
  NULL AS rewards_time_freezer_amount,
  NULL AS rewards_time_freezer_amount_type,
  NULL AS rewards_toss_amount,
  NULL AS rewards_toss_amount_type,
  session_id,
  session_time,
  NULL AS source,
  NULL AS special_offer_details_id,
  NULL AS status,
  NULL AS step,
  NULL AS step_index,
  NULL AS step_name,
  NULL AS store_visit_source,
  streak_breaker,
  NULL AS tap_count,
  targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  tiles_on_board,
  time_begin,
  time_remain,
  total_attempt_at_current_level,
  total_tile_count,
  NULL AS try,
  NULL AS tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  NULL AS visible_area,
  NULL AS welcome_back_day,
  NULL AS welcome_back_period,
  NULL AS win_count_elo_score

FROM
  tile_match.progression

UNION ALL

SELECT
  NULL AS action,
  NULL AS active_fail_safe_scenario,
  NULL AS active_item_count,
  NULL AS active_item_count_int,
  advertising_id,
  NULL AS amount,
  app_version,
  NULL AS apps_flyer_response_time,
  arrival_ts,
  NULL AS asset,
  NULL AS boosters,
  build_no,
  NULL AS building_item_count,
  NULL AS business_event_name,
  NULL AS completed_ad_count,
  NULL AS completed_rewarded_count_alltime,
  NULL AS completed_rewarded_count_in_day,
  NULL AS completed_rewarded_count_in_session,
  connection_type,
  NULL AS conversion_data,
  NULL AS currency_change_avatar_amount_type,
  NULL AS currency_change_avatar_change_amount,
  NULL AS currency_change_avatar_current_amount,
  NULL AS currency_change_avatar_frame_amount_type,
  NULL AS currency_change_avatar_frame_change_amount,
  NULL AS currency_change_avatar_frame_current_amount,
  NULL AS currency_change_coin_amount_type,
  NULL AS currency_change_coin_change_amount,
  NULL AS currency_change_coin_current_amount,
  NULL AS currency_change_environment_token_amount_type,
  NULL AS currency_change_environment_token_change_amount,
  NULL AS currency_change_environment_token_current_amount,
  NULL AS currency_change_event_score_multiplier_amount_type,
  NULL AS currency_change_event_score_multiplier_change_amount,
  NULL AS currency_change_event_score_multiplier_current_amount,
  NULL AS currency_change_event_token_amount_type,
  NULL AS currency_change_event_token_change_amount,
  NULL AS currency_change_event_token_current_amount,
  NULL AS currency_change_extra_slot_amount_type,
  NULL AS currency_change_extra_slot_change_amount,
  NULL AS currency_change_extra_slot_current_amount,
  NULL AS currency_change_extra_time_amount_type,
  NULL AS currency_change_extra_time_change_amount,
  NULL AS currency_change_extra_time_current_amount,
  NULL AS currency_change_glove_amount_type,
  NULL AS currency_change_glove_change_amount,
  NULL AS currency_change_glove_current_amount,
  NULL AS currency_change_life_amount_type,
  NULL AS currency_change_life_change_amount,
  NULL AS currency_change_life_current_amount,
  NULL AS currency_change_magic_wand_amount_type,
  NULL AS currency_change_magic_wand_change_amount,
  NULL AS currency_change_magic_wand_current_amount,
  NULL AS currency_change_magnet_amount_type,
  NULL AS currency_change_magnet_change_amount,
  NULL AS currency_change_magnet_current_amount,
  NULL AS currency_change_reward_multiplier_amount_type,
  NULL AS currency_change_reward_multiplier_change_amount,
  NULL AS currency_change_reward_multiplier_current_amount,
  NULL AS currency_change_shuffle_amount_type,
  NULL AS currency_change_shuffle_change_amount,
  NULL AS currency_change_shuffle_current_amount,
  NULL AS currency_change_time_freezer_amount_type,
  NULL AS currency_change_time_freezer_change_amount,
  NULL AS currency_change_time_freezer_current_amount,
  NULL AS currency_change_toss_amount_type,
  NULL AS currency_change_toss_change_amount,
  NULL AS currency_change_toss_current_amount,
  NULL AS currency_code,
  NULL AS daily_day,
  NULL AS daily_period_index,
  NULL AS daily_reward_id,
  NULL AS daily_reward_id_string,
  NULL AS deeplink_event_args,
  NULL AS difficulty,
  NULL AS difficulty_rank,
  NULL AS displayed_ad_count,
  NULL AS displayed_ad_count_in_level,
  NULL AS displayed_rewarded_count_alltime,
  NULL AS displayed_rewarded_count_in_day,
  NULL AS displayed_rewarded_count_in_session,
  NULL AS duration,
  NULL AS end_game_offer,
  NULL AS end_game_offer_10_bonus_slot,
  NULL AS end_game_offer_10_bonus_time,
  NULL AS end_game_offer_10_fail_type,
  NULL AS end_game_offer_10_offer_type,
  NULL AS end_game_offer_1_bonus_slot,
  NULL AS end_game_offer_1_bonus_time,
  NULL AS end_game_offer_1_fail_type,
  NULL AS end_game_offer_1_offer_type,
  NULL AS end_game_offer_2_bonus_slot,
  NULL AS end_game_offer_2_bonus_time,
  NULL AS end_game_offer_2_fail_type,
  NULL AS end_game_offer_2_offer_type,
  NULL AS end_game_offer_3_bonus_slot,
  NULL AS end_game_offer_3_bonus_time,
  NULL AS end_game_offer_3_fail_type,
  NULL AS end_game_offer_3_offer_type,
  NULL AS end_game_offer_4_bonus_slot,
  NULL AS end_game_offer_4_bonus_time,
  NULL AS end_game_offer_4_fail_type,
  NULL AS end_game_offer_4_offer_type,
  NULL AS end_game_offer_5_bonus_slot,
  NULL AS end_game_offer_5_bonus_time,
  NULL AS end_game_offer_5_fail_type,
  NULL AS end_game_offer_5_offer_type,
  NULL AS end_game_offer_6_bonus_slot,
  NULL AS end_game_offer_6_fail_type,
  NULL AS end_game_offer_6_offer_type,
  NULL AS end_game_offer_7_bonus_slot,
  NULL AS end_game_offer_7_bonus_time,
  NULL AS end_game_offer_7_fail_type,
  NULL AS end_game_offer_7_offer_type,
  NULL AS end_game_offer_8_bonus_slot,
  NULL AS end_game_offer_8_bonus_time,
  NULL AS end_game_offer_8_fail_type,
  NULL AS end_game_offer_8_offer_type,
  NULL AS end_game_offer_9_bonus_slot,
  NULL AS end_game_offer_9_bonus_time,
  NULL AS end_game_offer_9_fail_type,
  NULL AS end_game_offer_9_offer_type,
  NULL AS environment_id,
  NULL AS error_string,
  NULL AS event_data_business_id,
  event_id,
  event_name,
  event_previous_id,
  event_timestamp,
  event_type,
  event_version,
  NULL AS fail_type,
  NULL AS goodwill_pass_purchase_details_pass_type,
  NULL AS goodwill_pass_purchase_details_start_date,
  NULL AS goodwill_pass_purchase_details_step,
  NULL AS initialized,
  installed_at,
  inventory_avatar,
  inventory_coin,
  inventory_environment_token,
  inventory_event_score_multiplier,
  inventory_event_token,
  inventory_extra_slot,
  inventory_extra_time,
  inventory_glove,
  inventory_life,
  inventory_magic_wand,
  inventory_magnet,
  inventory_shuffle,
  inventory_time_freezer,
  inventory_toss,
  ip_address,
  NULL AS item_id,
  NULL AS last_input_time,
  NULL AS live_ops_bonus_bank_max_score,
  NULL AS live_ops_bonus_bank_reward_collected,
  NULL AS live_ops_bonus_bank_score,
  NULL AS live_ops_chest_index,
  NULL AS live_ops_claimed_stage,
  NULL AS live_ops_complete_ratio,
  NULL AS live_ops_connection_error,
  NULL AS live_ops_default_stage_count,
  NULL AS live_ops_default_stage_index,
  NULL AS live_ops_difficulty,
  NULL AS live_ops_elo_rank,
  NULL AS live_ops_engagement_type,
  NULL AS live_ops_event_name,
  NULL AS live_ops_id,
  NULL AS live_ops_is_accepted,
  NULL AS live_ops_is_bonus,
  NULL AS live_ops_is_free,
  NULL AS live_ops_pass_type,
  NULL AS live_ops_purchase_source,
  NULL AS live_ops_quest,
  NULL AS live_ops_racers_group_id,
  NULL AS live_ops_ranking,
  NULL AS live_ops_score,
  NULL AS live_ops_start_date,
  NULL AS live_ops_start_time,
  NULL AS live_ops_step,
  NULL AS live_ops_store_open_source,
  NULL AS live_ops_target,
  NULL AS live_ops_template_id,
  NULL AS live_ops_type,
  NULL AS min_day_condition,
  NULL AS monthly_day,
  NULL AS monthly_period_index,
  NULL AS monthly_reward_id,
  NULL AS monthly_reward_id_string,
  NULL AS move_count,
  NULL AS obstacles,
  NULL AS occured_issue,
  NULL AS package_coefficient,
  NULL AS package_id,
  NULL AS package_order,
  NULL AS pay_and_proceed_purchase_details_start_day,
  NULL AS pay_and_proceed_purchase_details_step,
  NULL AS pay_and_proceed_purchase_details_template_id,
  NULL AS period_index,
  NULL AS play_time_elo_score,
  NULL AS position,
  NULL AS previous_event_id,
  NULL AS purchase_source,
  NULL AS reason,
  NULL AS receipt_info,
  NULL AS remain_tile_count,
  request_time,
  NULL AS response,
  NULL AS response_time,
  NULL AS rewarded_ad_limit_in_day,
  NULL AS rewarded_ad_limit_in_session,
  NULL AS rewarded_ad_type,
  NULL AS rewards_avatar_amount,
  NULL AS rewards_avatar_amount_type,
  NULL AS rewards_avatar_frame_amount,
  NULL AS rewards_avatar_frame_amount_type,
  NULL AS rewards_bonus_slot_amount,
  NULL AS rewards_bonus_slot_amount_type,
  NULL AS rewards_bonus_time_amount,
  NULL AS rewards_bonus_time_amount_type,
  NULL AS rewards_coin_amount,
  NULL AS rewards_coin_amount_type,
  NULL AS rewards_environment_token_amount,
  NULL AS rewards_environment_token_amount_type,
  NULL AS rewards_event_score_multiplier_amount,
  NULL AS rewards_event_score_multiplier_amount_type,
  NULL AS rewards_event_token_amount,
  NULL AS rewards_event_token_amount_type,
  NULL AS rewards_extra_slot_amount,
  NULL AS rewards_extra_slot_amount_type,
  NULL AS rewards_extra_time_amount,
  NULL AS rewards_extra_time_amount_type,
  NULL AS rewards_glove_amount,
  NULL AS rewards_glove_amount_type,
  NULL AS rewards_life_amount,
  NULL AS rewards_life_amount_type,
  NULL AS rewards_magic_wand_amount,
  NULL AS rewards_magic_wand_amount_type,
  NULL AS rewards_magnet_amount,
  NULL AS rewards_magnet_amount_type,
  NULL AS rewards_reward_multiplier_amount,
  NULL AS rewards_reward_multiplier_amount_type,
  NULL AS rewards_shuffle_amount,
  NULL AS rewards_shuffle_amount_type,
  NULL AS rewards_time_freezer_amount,
  NULL AS rewards_time_freezer_amount_type,
  NULL AS rewards_toss_amount,
  NULL AS rewards_toss_amount_type,
  session_id,
  session_time,
  NULL AS source,
  NULL AS special_offer_details_id,
  NULL AS status,
  NULL AS step,
  NULL AS step_index,
  NULL AS step_name,
  NULL AS store_visit_source,
  NULL AS streak_breaker,
  NULL AS tap_count,
  NULL AS targets,
  team_activity,
  team_id,
  team_name,
  team_score,
  team_size,
  team_user_life_help_count,
  team_user_life_req_count,
  team_user_lifetime_life_help_count,
  team_user_lifetime_life_req_count,
  team_user_lifetime_message_count,
  team_user_message_count,
  NULL AS tiles_on_board,
  NULL AS time_begin,
  NULL AS time_remain,
  NULL AS total_attempt_at_current_level,
  NULL AS total_tile_count,
  NULL AS try,
  NULL AS tutorial_name,
  user_active_events,
  user_adgroup,
  user_af_campaign,
  user_af_campaign_code,
  user_apps_flyer_id,
  user_available_events,
  user_avatar_id,
  user_balance_version,
  user_bonus_level_at,
  user_campaign,
  user_campaign_code,
  user_country_code,
  user_creative,
  user_current_elo_score,
  user_current_fps,
  user_device,
  user_difficulty_elo_score,
  user_elo_rank,
  user_game_mode,
  user_grand_mode_level,
  user_id,
  user_is_bonus_mode_active,
  user_level_at,
  user_level_id,
  user_level_id_string,
  user_manufacturer,
  user_network,
  user_notification_state,
  user_os_version,
  user_pass_stage,
  user_pass_type,
  user_platform,
  user_remote_config_update_date,
  user_session_count,
  user_split_test_name,
  user_test_routing_value,
  user_total_attempt_at_current_lvl,
  user_total_payment,
  user_total_session_time,
  user_total_valid_attempt_at_current_level,
  user_win_streak_count,
  user_win_streak_group,
  NULL AS visible_area,
  NULL AS welcome_back_day,
  NULL AS welcome_back_period,
  NULL AS win_count_elo_score

FROM tile_match.session) AS combined_data) ;;

    publish_as_db_view: yes
    sql_trigger_value: select DATE_TRUNC('day',DATEADD('minute', -540 , getdate() )  )  ;;
    sortkeys: ["advertising_id"]
  }

  dimension: advertising_id {
    type: string
    sql: ${TABLE}.advertising_id ;;
  }
}
